# Generated by Django 5.0.2 on 2024-03-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(default='https://jonbancroft.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutMe.project')),
            ],
        ),
    ]
